For consistency use png on macOS
1Password/arboard pull request #110
Opened 2023-08-24 11:15 UTC by VZout

Instead of storing as png on linux and tiff on macos, it feels nicer to just store it as png everywhere.

2023-08-24 11:26 UTC, VZout commented on Cargo.toml
> +image-data = ["dep:core-graphics", "dep:image", "winapi/minwindef", "winapi/wingdi", "winapi/winnt"]
This makes the feature flags in the docs a bit more readable as right now it shows `image`, `core-graphics` and `wl-clipboard-rs` as "features" but they are just optional dependencies

2023-08-26 02:27 UTC, complexspaces commented
Thanks for the PR. I think this change makes sense as long as it doesn't break copying compatibility in any noticeable way. Could I ask you to try some testing by copying images from various apps/websites to see if there's a difference in what `NSPasteboard` can convert into a `.png` vs a `.tiff`?

2023-08-26 02:54 UTC, complexspaces requested changes
Regarding my comment about compatibility testing, I got a little bit ahead of myself since I didn't look at the code first. Sorry. Feel free to play around on my other PR though where you could fit PNG reading in though.

2023-08-26 02:54 UTC, complexspaces commented on Cargo.toml
> +image-data = ["dep:core-graphics", "dep:image", "winapi/minwindef", "winapi/wingdi", "winapi/winnt"]
FWIW, this requires a bump to Rust 1.60 to support:
>  The dep: syntax is only available starting with Rust 1.60. Previous versions can only use the implicit feature name.

`arboard` doesn't currently have an MSRV, and 1.60 is over a year old at this point, so I don't think its a big deal. Its also easy enough to rollback if it causes someone problems. I'm mentioning it just in case though.

2023-08-26 02:54 UTC, complexspaces commented on src/platform/osx.rs
> +		let png: &NSArray<NSObject> = unsafe { msg_send![obj, PNGRepresentation] };
I don't believe NSImage supports this representation (and is causing [a test failure](https://github.com/1Password/arboard/actions/runs/5962987149/job/16202321208?pr=110)), [unlike UIImage which does](https://developer.apple.com/documentation/uikit/1624096-uiimagepngrepresentation?language=objc).

One alternative may be to wait for https://github.com/1Password/arboard/pull/106 to merge which switches to a different method of getting images from the clipboard. That way [does support PNG](https://developer.apple.com/documentation/appkit/nspasteboardtypepng?language=objc) like you'd want.

2025-08-25 01:43 UTC, complexspaces commented
Closing in favor of https://github.com/1Password/arboard/pull/164 or future PRs doing similar.

2025-08-25 01:43 UTC, closed without merging