Update clipboard-win to v5 and replace winapi with windows-rs
1Password/arboard pull request #123
Opened 2023-11-24 03:02 UTC by rhysd

This PR does two things for Windows support:

1. Update clipboard-win to v5.0.0
   - I checked [changes in v5.0.0](https://github.com/DoumanAsh/clipboard-win/compare/44487b19cd12a9242f5b1991c088bf81c780f172...973219a363729dcaeb98ba74280f3543322f37d7) and there was no API change at v5
3. Replace `winapi` crate dependency with `windows-rs`
   - winapi is unmaintained. windows-rs is well-maintained by Microsoft officially
   - By this change, winapi can be removed completely from this crate
   - The replacement is somewhat mechanical translation from winapi to windows-rs. I read MSDN documents but my understanding of the Win32 APIs is not perfect. I'd like to have detailed code review

I confirmed writing/reading clipboard with both text and image contents using `hello_world` and `set_image`/`get_image` examples on my Windows 10 machine.

With this PR, cargo dependencies will change to:

```console
> cargo tree --edges no-dev
arboard v3.3.0
├── clipboard-win v5.0.0
│   └── error-code v3.0.0
├── log v0.4.20
├── thiserror v1.0.35
│   └── thiserror-impl v1.0.35 (proc-macro)
│       ├── proc-macro2 v1.0.43
│       │   └── unicode-ident v1.0.4
│       ├── quote v1.0.21
│       │   └── proc-macro2 v1.0.43 (*)
│       └── syn v1.0.100
│           ├── proc-macro2 v1.0.43 (*)
│           ├── quote v1.0.21 (*)
│           └── unicode-ident v1.0.4
└── windows v0.52.0
    ├── windows-core v0.52.0
    │   └── windows-targets v0.52.0
    │       └── windows_x86_64_msvc v0.52.0
    └── windows-targets v0.52.0 (*)
```

2023-11-27 17:38 UTC, complexspaces commented
Thanks for the PR, I appreciate the effort. Would you consider modifying this to use `windows-sys` instead of the `windows` crate? The former has much less version churn and I'm not sure how much value `arboard` gets out of using `windows` because we don't utilize any COM or WinRT logic.

I would definitely be in favor of implementing a helper function to wrap some of the `Global*` calls to handle checking for errors internally though.

2023-11-28 01:07 UTC, rhysd commented
It makes sense. I'll try windows-sys.

2023-11-28 03:07 UTC, rhysd commented
> I would definitely be in favor of implementing a helper function to wrap some of the Global* calls to handle checking for errors internally though.

I focused on replacing winapi with windows-rs with as small diff as possible. But I'll refactor the code more idiomtic.

2023-11-28 03:22 UTC, complexspaces commented
No worries either way, I could refactor it later if you are busy. I generally don't mind a little bit of scope creep in PRs that touches the same area as long as its independently reviewable (its own commit, etc).

2023-11-28 03:39 UTC, rhysd commented
No, problem. I like refactorying so I'll try it by myself :)

2023-11-28 04:27 UTC, rhysd commented on src/platform/windows.rs
> +mod image_data {
Separating this module as a new file may be a good idea.

2023-11-28 04:32 UTC, rhysd commented
I added some refactorings:

- 6cfde9c39e8c0071d52ec0862614af7b14433b16 : Add `Error::unknown` helper function to avoid `Error::Unknown { ... }` boilerplate
- ec5e1d86eaaeec8e6894305949cacb3353f335bb : Separate the implementation details of image data handling into `image_data` module to avoid many repeats of `#[cfg(feature = "image-data")]` gates. Moving the module to a new file may be a good idea (I don't have a strong opinion here).
- ba5575bf843f57463874c0289fd82a6db909229c : Wrap Win32 functions which can return errors to leverage error handling with `?` operator. This made `add_cf_dibv5` and `read_cf_dibv5` simpler
- ba9e7e84c89f880ac930049155b325267aa3156a : Move tests for image data handling to `image_data` module and added more test cases

2023-11-28 05:25 UTC, rhysd commented
The dependency tree is now:

```console
> cargo tree --edges no-dev
arboard v3.3.0
├── clipboard-win v5.0.0
│   └── error-code v3.0.0
├── log v0.4.20
├── thiserror v1.0.35
│   └── thiserror-impl v1.0.35 (proc-macro)
│       ├── proc-macro2 v1.0.43
│       │   └── unicode-ident v1.0.4
│       ├── quote v1.0.21
│       │   └── proc-macro2 v1.0.43 (*)
│       └── syn v1.0.100
│           ├── proc-macro2 v1.0.43 (*)
│           ├── quote v1.0.21 (*)
│           └── unicode-ident v1.0.4
└── windows-sys v0.52.0
    └── windows-targets v0.52.0
        └── windows_x86_64_msvc v0.52.0
```

2023-11-30 19:48 UTC, complexspaces requested changes

2023-11-30 19:48 UTC, complexspaces commented on src/platform/windows.rs
> +	unsafe fn get_screen_device_context() -> Result<HDC, Error> {
Suggestion: This doesn't need to be `unsafe` because `GetDc` doesn't have any safety conditions to uphold beyond the parameter?

2023-11-30 19:48 UTC, complexspaces commented on src/platform/windows.rs
> +	/// returns value is the number of scan lines copied from the bitmap.
```suggestion
	/// Copies the bitmap image into given buffer with DIB RGB format and
	/// returns the number of scan lines copied from the bitmap.
```

2023-12-01 01:36 UTC, rhysd commented
Thank you for your reviews. I'll have a look at them tonight.

2023-12-01 15:26 UTC, rhysd commented on src/platform/windows.rs
> +	unsafe fn set_clipboard_data(hmem: HANDLE) -> Result<(), Error> {
I created a separate function here because it returns an error and we can levarate `?` error handling to reduce size of big function `add_cf_dibv5`. I agree with the name is not good.

2023-12-01 15:33 UTC, rhysd commented on src/platform/windows.rs
> +		Error::unknown(format!("{} with error code {:x}", message, code))
I didn't know the function. It's definitely better.

2023-12-01 15:36 UTC, rhysd commented on src/platform/windows.rs
> +				if GlobalUnlock(hdata) == 0 {
Ahh, I misread the MSDN document. I think I overlooked the error log on checking the examples.

2023-12-01 15:37 UTC, rhysd commented on src/platform/windows.rs
> +	unsafe fn get_screen_device_context() -> Result<HDC, Error> {
Yeah, it is actually safe. I made this function safe with a `SAFETY:` comment.

2023-12-01 15:38 UTC, rhysd commented
@complexspaces I replied to your review comments and fixed all points. Would you take a look again?

2023-12-01 17:46 UTC, complexspaces commented on src/platform/windows.rs
> +				if GlobalUnlock(hdata) == 0 {
I'm still not sure here yet, sorry.

This is the MSDN snippet I've been reading:
> If the memory object is still locked after decrementing the lock count, the return value is a nonzero value. If the memory object is unlocked after decrementing the lock count, the function returns zero and [GetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror) returns NO_ERROR.
>
> If the function fails, the return value is zero and [GetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror) returns a value other than NO_ERROR.

AFAICT, an real error that we would need to log comes from both:
- `GlobalUnlock == 0`
- `LastError != 0`

The `-1` value that is being checked for now doesn't seem to be an error, and is instead just a valid result of calling the function.

2023-12-03 07:52 UTC, rhysd commented on src/platform/windows.rs
> +				if GlobalUnlock(hdata) == 0 {
Ohh, thank you for the point. Since I don't have time to look into this for now, I'll take a look on next Monday.

2023-12-04 19:28 UTC, complexspaces approved these changes
Thanks a lot for your work on this, everything looks good now!

2023-12-04 20:52 UTC, merged