Document errors on Clipboard
1Password/arboard pull request #127
Opened 2023-12-29 18:42 UTC by robjtede

depends on #126

2024-01-02 18:04 UTC, robjtede commented on src/common.rs
> +	/// converted to the appropriate format.
these cases are better documented on the methods themselves; remove from here to prevent de-sync

2024-01-02 18:05 UTC, complexspaces requested changes
Do you mind squashing/rebasing on `main` as well? I can also handle it if you would rather not but I try not to use merge commits.

2024-01-02 18:05 UTC, complexspaces commented on src/lib.rs
> +/// multiple `Clipboard`s may not exist at once (on the same thread). This also means that
On Windows this is a system-wide limitation (so for `arboard`'s documentation, per process), not per-thread. The lack of `Send+Sync` there is a lint to try and stop you from getting into this state when assuming other apps are behaving right.

2024-01-02 18:10 UTC, robjtede commented on src/lib.rs
> +/// multiple `Clipboard`s may not exist at once (on the same thread). This also means that
I think we agree on the problem here but maybe this tweak is not very good. How do you want this to read? Maybe an explicit call out to the user that they should avoid creating/operating on clipboard objects on >1 threads? That's not something that the !Send+!Sync can prevent.

2024-01-02 18:42 UTC, robjtede commented
> Do you mind squashing/rebasing on main as well

sure, can do

> I try not to use merge commits

does this repo not allow squash merging?

2024-01-08 15:55 UTC, complexspaces commented on src/lib.rs
> +/// multiple `Clipboard`s may not exist at once (on the same thread). This also means that
> Maybe an explicit call out to the user that they should avoid creating/operating on clipboard objects on >1 threads?

That sounds good to me. Its likely easier for the user to reason about not creating more then 1 across >1 thread then creating N clipboards and manually synchronizing them.

> That's not something that the !Send+!Sync can prevent.

I know it isn't, but it does help with the Windows requirement of per-thread clipboarding. If you send the clipboard object to another thread, it won't behave correctly.

2024-01-19 02:16 UTC, robjtede commented on src/lib.rs
> +/// multiple `Clipboard`s may not exist at once (on the same thread). This also means that
Thoughts on the new wording? @complexspaces

2024-01-19 02:27 UTC, complexspaces requested changes

2024-01-19 02:27 UTC, complexspaces commented on src/lib.rs
> +/// This means that attempting operations in parallel has a high likelihood to return an error. As
```suggestion
/// This means that attempting operations in parallel has a high likelihood to return an error or deadlock. As
```

2024-01-19 02:27 UTC, complexspaces commented on src/lib.rs
> +	/// supported.
```suggestion
	/// supported. This may be retried. 
```

2024-01-19 02:27 UTC, complexspaces commented on src/lib.rs
> +	/// Returns error if clipboard is empty or contents is not UTF-8 text.
```suggestion
	/// Returns error if clipboard is empty or contents are not UTF-8 text.
```

2024-01-19 02:27 UTC, complexspaces commented on src/lib.rs
> +	/// Returns error if clipboard is empty, contents is not an image, or contents cannot be
```suggestion
	/// Returns error if clipboard is empty, contents are not an image, or the contents cannot be
```

2024-01-19 02:28 UTC, complexspaces commented on src/lib.rs
> +/// multiple `Clipboard`s may not exist at once (on the same thread). This also means that
Sorry, I missed the notification for the most recent push to the branch. I left one more nit on this phrasing but otherwise I think it looks good to go 👍

2024-01-22 17:04 UTC, complexspaces approved these changes
Thanks!

2024-01-22 17:05 UTC, merged