Add `SetExtLinux#wait_until`
1Password/arboard pull request #134
Opened 2024-02-22 18:41 UTC by auguwu

Hello :wave:!

I added a `wait_until` method on [`SetExtLinux`](https://github.com/1Password/arboard/blob/77e0e078eb460ac2fa0eda96124163c11ef6b2d1/src/platform/linux/mod.rs#L181) for X11 to wait until a deadline was exceeded so that:

* You wouldn't need a daemon process to call `wait` on.
* Easier for CLI programs who don't want to infinitely loop / wait for new contents to be replaced & want to finish quickly.

This does report the following log when used:
```sh
2024-02-22T18:28:30.515424Z  WARN arboard::platform::linux::x11: Could not hand the clipboard contents over to the clipboard manager. The request timed out.
```

since `result.timed_out` is used and I'm not too sure what to do in this case:
https://github.com/1Password/arboard/blob/77e0e078eb460ac2fa0eda96124163c11ef6b2d1/src/platform/linux/x11.rs#L711-L715

2024-04-09 22:14 UTC, complexspaces requested changes
I apologize for the review delay on this PR. I think this is reasonably useful functionality given how weird Linux can be, and it doesn't conflict with anything else.

2024-04-09 22:14 UTC, complexspaces commented on src/platform/linux/mod.rs
> +	wait_until: Option<Instant>,
Suggestion: I believe this would be better if we refactored these away into a single enum representing the possible cases:
```rust
enum WaitConfig {
    None,
    Forever,
    Until(Instant)
}
```

It would also reduce the amount of parameters in the various `set` functions and simplify the state handling via `match`.

2024-04-09 22:14 UTC, complexspaces commented on src/platform/linux/mod.rs
> +	fn wait_until(self, deadline: Instant) -> Self;
Please move this underneath `wait` so the related methods are grouped together.

2024-04-09 22:14 UTC, complexspaces commented on src/platform/linux/mod.rs
> +	/// Note: this will call [`wait()`][SetExtLinux::wait] if it wasn't previously set.
```suggestion
	/// Note: this is a superset of [`wait()`][SetExtLinux::wait] and will overwrite any state that was previously set using it.
```

2024-04-09 22:14 UTC, complexspaces commented on src/platform/linux/mod.rs
> +	/// were added and will exit as so.
```suggestion
	/// This is useful for short-lived programs so that it doesn't block until new contents on the clipboard
	/// were added and will exit automatically once the specified deadline has elapsed.
```

2024-04-09 22:25 UTC, auguwu commented
I can do that as soon as I can. Also, is the WARN log message ok to be emitted or can it be removed?

2024-04-09 22:29 UTC, complexspaces commented
As far as I know, the `warn` log is working as intended and unrelated to your changes here. Do you have a clipboard manager on your system? And are you able to share the code you used to test this?

2024-04-09 23:04 UTC, auguwu commented
I was able to test it and it does work correctly when I made this PR. I'll test it again and see if it still works once I can fix the suggested changes.

I'm not sure how to do unit tests for this though so I might have to dig through how the 'wait' function does its tests

2024-04-10 00:05 UTC, auguwu commented on src/platform/linux/mod.rs
> +	fn wait_until(self, deadline: Instant) -> Self;
I'm not sure which section that the contents should go into

2024-04-10 01:31 UTC, auguwu commented
> And are you able to share the code you used to test this?

I am using it for the purposes of [`auguwu/ume`](https://github.com/auguwu/ume), which uses arboard to copy a link when taking a screenshot (`ume screenshot`). It really boils down to this:

```rust
// the code that does the copying
let mut clipboard = arboard::Clipboard::new()?;
cfg_if::cfg_if! {
  if #[cfg(target_os = "linux")] {
      use arboard::SetExtLinux;

      // wait ~1s to block
      clipboard.set().wait_until(Instant::now() + Duration::from_secs(1)).text(url)?;
    } else {
      clipboard.set_text(url)?;
    }
  }
}
```

and this is how the application reacts to it:
```console
$ UME_UPLOADER_KEY="1234" cargo run -- screenshot http://localhost:3621
2024-04-10T01:30:11.430927Z  INFO ume::cli::cmds::screenshot: found `flameshot` program :3 flameshot=/run/current-system/sw/bin/flameshot
2024-04-10T01:30:11.431155Z  INFO ume::cli::cmds::screenshot: creating file... file=/tmp/screenshots/2024-04-09T18:30:11.430982407-07:00.png
2024-04-10T01:30:11.432066Z  INFO ume::cli::cmds::screenshot: $ /run/current-system/sw/bin/flameshot gui -r > /tmp/screenshots/2024-04-09T18:30:11.430982407-07:00.png
2024-04-10T01:30:17.069959Z  INFO ume::cli::cmds::screenshot: uploading file to Ume server... file=/tmp/screenshots/2024-04-09T18:30:11.430982407-07:00.png
2024-04-10T01:30:17.070032Z  INFO ume::cli::cmds::screenshot: Now uploading file... file=/tmp/screenshots/2024-04-09T18:30:11.430982407-07:00.png
2024-04-10T01:30:17.149519Z  INFO ume::cli::cmds::screenshot: copying url to clipboard!
2024-04-10T01:30:18.150255Z  INFO ume::cli::cmds::screenshot: copied to clipboard, deleting image
2024-04-10T01:30:18.250519Z  WARN arboard::platform::linux::x11: Could not hand the clipboard contents over to the clipboard manager. The request timed out.
```

and it'll copy `http://localhost:3621/images/{random characters}.png` to the clipboard.

2024-04-10 22:34 UTC, complexspaces commented on src/platform/linux/mod.rs
> +	fn wait_until(self, deadline: Instant) -> Self;
Sorry, I meant to indicate that this this function (and its documentation) should be moved above `fn clipboard` but below `fn wait` in the trait definition.

2024-04-10 22:40 UTC, complexspaces commented on src/platform/linux/mod.rs
> +	wait_until: Option<Instant>,
@auguwu Your last changeset brought this most of the way, but the fields inside `struct Set` should also get replaced with the new enum. You'll need to bring `WaitConfig` up into `mod.rs` as well and update the `wayland` module to handle the `Forever` case.

The `fn wait` and `fn wait_until` methods should then look something like this:
```rust
fn wait(mut self) -> Self {
    self.platform.wait = WaitConfig::Forever;
    self
}

fn wait_until(mut self, deadline: Instant) -> Self {
    self.platform.wait = WaitConfig::Until(deadline);
    self
}
```

2024-04-10 22:40 UTC, complexspaces commented on src/platform/linux/x11.rs
> +pub enum WaitConfig {
```suggestion
pub(crate) enum WaitConfig {
```

2024-04-11 19:01 UTC, auguwu commented
I should fix everything that was suggested!

2024-04-12 20:13 UTC, complexspaces approved these changes

2024-04-12 20:13 UTC, merged

2024-04-12 20:14 UTC, complexspaces commented
Thanks again for the PR, and additionally thank you for the `TRACE` logs using `arboard` on your system. It seems like something is amiss in the clipboard ordering handoff but that can happen in another pull request/issue for sure.

2024-11-09 16:21 UTC, LOHAYBOY999 approved these changes