Add support for excluding macos clipboard items from history
1Password/arboard pull request #159
Opened 2024-08-02 11:36 UTC by Hinton

This follows the Windows strategy of introducing a Set Extension for excluding items from history in MacOS. It's implemented mostly the same way with every set action calling a `add_clipboard_exclusions` function.

As there isn't technically an official standard it uses the community standard of setting `org.nspasteboard.ConcealedType` from http://nspasteboard.org/. I've manually tested this using the Maccy clipboard manager and with `exclude_history` items are no longer tracked.

I was a bit uncertain about the naming of the new trait as it could also be called `SetExtMac` but I decided to follow the filename.

2024-08-24 21:37 UTC, complexspaces requested changes
Hey there, thank you for the PR! I apologize for my untimely review. Please rebase this on `master to pick up https://github.com/1Password/arboard/pull/161 and fix the unrelated CI errors.

I tried this one out locally and the functionality looks good to go! I'm happy to merge this one once the trait rename I've suggested is implemented.

2024-08-24 21:37 UTC, complexspaces commented on src/platform/osx.rs
> +	/// http://nspasteboard.org/
Nit:
```suggestion
	/// See http://nspasteboard.org/ for details about the community standard.
```

2024-08-24 21:37 UTC, complexspaces commented on src/platform/osx.rs
> +/// OS X-specific extensions to the [`Set`](crate::Set) builder.
Nit:
```suggestion
/// OSX-specific extensions to the [`Set`](crate::Set) builder.
```

2024-08-24 21:37 UTC, complexspaces commented on src/platform/osx.rs
> +pub trait SetExtOsx: private::Sealed {
Do you remind renaming this to `SetAppleExt`, please? I want to add iOS support in the near-future and it would be great to do so without needing a breaking change later to make it's name accurate again.

2024-08-27 12:56 UTC, Hinton commented on src/platform/osx.rs
> +/// OS X-specific extensions to the [`Set`](crate::Set) builder.
I changed this to `Apple` to match the updated name.

2024-08-27 12:57 UTC, Hinton commented
@complexspaces no worries.

I've resolved the review feedback.

2024-08-27 18:09 UTC, complexspaces approved these changes
This looks good to go now, thanks again.

I can most likely make a new release with these changes for you by early next week.

2024-08-27 18:10 UTC, merged

2024-09-12 15:40 UTC, complexspaces commented
This is now released in [v3.4.1](https://github.com/1Password/arboard/releases/tag/v3.4.1) on crates.io. Thanks again for the PR!