Support waiting on the clipboard to be overwritten on Linux
1Password/arboard pull request #43
Opened 2022-04-08 14:49 UTC by SabrinaJewson

Note: Untested on Wayland.

Fixes: #39

2022-04-15 02:48 UTC, MattX commented
Thanks, I think this would be really useful–under most X11 desktop environments, this is probably what most users want to call. For what it's worth, the code looks good to me!

Have you considered adding a timeout (probably fairly easy using `wait_timeout`)? I have a use case that would benefit from that: I want to give a few hundred ms to a clipboard manager to take the clipboard over, and just fail otherwise instead of hanging.

2022-04-15 09:06 UTC, SabrinaJewson commented
I did originally have `wait_timeout`, but removed it when I realized that `wl-clipboard-rs` doesn't support the operation. Maybe it's something that could be added in future though, if `wl-clipboard-rs` gets that functionality.

2022-04-15 19:20 UTC, MattX commented
Ah, that's unfortunate but it makes sense.

2022-04-18 14:25 UTC, complexspaces commented
Hey, thanks for the PR! I'll try and make some time this week to review what's here.

2022-05-02 15:20 UTC, complexspaces reviewed
Overall, I think this seems like a solid proposal. I've left a few very small nits. I apologize for the delay getting around to this as well 😞.

 I'm curious to see if @arturmartins or @mathieulj have any strong opinions one way or another.

2022-05-02 15:42 UTC, SabrinaJewson commented on examples/daemonize.rs
> +	if env::args().nth(1).as_deref() == Some("__internal_daemonize") {
Good idea!

2022-05-19 16:18 UTC, SabrinaJewson commented
I think I still prefer my version of that API, because to me it makes sense that setting the clipboard and waiting for the serving to complete should be a single atomic operation. The combined API also might enable a future optimization of not spawning another thread when it’s not necessary, which may be desirable.

Another option is to create a builder API [like `wl-clipboard-rs` has](https://docs.rs/wl-clipboard-rs/latest/wl_clipboard_rs/copy/struct.Options.html). This avoids the method duplication problem and the current functions can still coexist as convenience functions.

> With Wayland, we could just re-implement the thread spawn that it does internally based on if `foreground` is set or not.

What do you mean by this? Are you saying that we’d always set `foreground` to run it in our own background thread and then somehow communicate with that thread inside `wait_for_change`?

2022-06-04 12:01 UTC, SabrinaJewson commented
I’ve now added a builder API to help address the combinatorial explosion problem. Basically, instead of `clipboard.set_wait(text)` you will now call `clipboard.set().wait(text)`. A sketch of the new API is below:

```rs
impl Clipboard {
    // Same methods as before, now rendered shortcut methods
    fn get_text(&mut self) -> Result<String, Error> { self.get().text() }
    fn set_text(&mut self, text: String) -> Result<(), Error> { self.set().text(text) }
    fn get_image(&mut self) -> Result<ImageData<'static>, Error> { self.get().image() }
    fn set_image(&mut self, image: ImageData<'_>) -> Result<(), Error> { self.set().image(image) }

    fn get(&mut self) -> Get<'_>;
    fn set(&mut self) -> Set<'_>;
}

impl<'clipboard> Get<'clipboard> {
    fn text(self) -> Result<String, Error>;
    fn image(self) -> Result<ImageData<'static>, Error>;
    // Linux-only via GetExtLinux
    fn text_with_clipboard(self, selection: LinuxClipboardKind) -> Result<String, Error>;
}

impl<'clipboard> Set<'clipboard> {
    fn text(self, text: String) -> Result<(), Error>;
    fn image(self, image: ImageData<'_>) -> Result<(), Error>;
    // Linux-only via SetExtLinux
    fn wait(self) -> Self;
    fn text_with_clipboard(self, text: String, selection: LinuxClipboardKind) -> Result<(), Error>;
}
```

Also, I noticed that `x11_clipboard`, `wayland_data_control_clipboard`, `osx_clipboard` and `windows_clipboard` were declared `pub mod`s in the source code — I’m assuming this is a mistake, since they’re very low-level. This commit also makes them private. I break the API of `X11ClipboardContext` in `x11_clipboard` anyway so I think it’s for the better.

2022-06-05 04:58 UTC, complexspaces requested changes
This looks great overall! Thank you for the extra time needed for implementing the builder pattern. 

I really like it and I think it will be useful for adding clipboard parameters to macOS and Windows in the future too.

2022-06-05 04:58 UTC, complexspaces commented on src/common_linux.rs
>  impl ClipboardExtLinux for super::Clipboard {
If a new major version is required anyway, I don't think there is much reason to keep this trait after the other new API additions. A user would already need to import a trait to use different clipboards so this one has no extra value AFAICT. Do you agree?

2022-06-05 04:58 UTC, complexspaces commented on src/lib.rs
> +			Arc,
I believe this `Arc` import needs moved into the Linux specific tests block to clean resolve these warnings. Thanks for tidying these up too!

2022-06-05 04:58 UTC, complexspaces commented
> Also, I noticed that x11_clipboard, wayland_data_control_clipboard, osx_clipboard and windows_clipboard were declared pub mods in the source code  — I’m assuming this is a mistake, since they’re very low-level...

That would be my best assumption, too. They seem like a remnant of the pattern that `rust-clipboard` originally had, but that would be a question for @ArturKovacs.

### Compatibility report:
- X11: None of the extra returned structures are useful at all. There are no APIs which use them. `X11ClipboardContext` is actually less-useful than the high-level `Clipboard` due to the lack of the extension trait.
- Wayland: `WaylandDataControlClipboardContext` can be constructed and used, but it doesn't provide any more features than the high-level `Clipboard`.
- macOS: `OSXClipboardCOntext` can't be constructed or used. There is also the `class` function, which removing from the public API would be a win too.
- Windows: `WindowsClipboardContext` can be constructed, but there is nothing a user could do with it.

2022-06-07 18:49 UTC, complexspaces approved these changes

2022-06-08 14:27 UTC, mathieulj approved these changes
Thank you for being patient with me, great work.

2022-06-08 14:27 UTC, mathieulj commented on src/common_linux.rs
> +	fn text_with_clipboard(self, selection: LinuxClipboardKind) -> Result<String, Error> {
This might not be usable for image data and departs a little further from the previous API but I'm interested in hearing your thoughts; could we also use the builder pattern for this one?

Ex. 
```rust	
pub(crate) fn new(clipboard: &'clipboard mut Clipboard) -> Self {
    Self { 
        clipboard,
        selection: LinuxClipboardKind::Clipboard
    }
}
```
```rust
fn clipboard(self, selection: LinuxClipboardKind) -> Self {
    Self {
        selection, 
        ..self
    }
}
```

```rust
ctx.set().clipboard(LinuxClipboardKind::Clipboard).text(TEXT1.to_string()).unwrap();
```

2022-06-08 16:45 UTC, SabrinaJewson commented on src/common_linux.rs
> +	fn text_with_clipboard(self, selection: LinuxClipboardKind) -> Result<String, Error> {
Originally I did have that API, but then I thought that because previously that because this library didn’t provide the functionality, X11 and Wayland didn’t support image data on primary and secondary clipboards. But it seems they do, so I’ve implemented that now!

2022-06-09 03:52 UTC, merged